stages:
  data_ingestion:
    cmd: python src/stages/data_ingestion.py
    deps:
      - src/stages/data_ingestion.py
      - data/raw/student_scores.csv
    outs:
      - data/processed/ingested_data.csv



  data_preprocessing:
    cmd: python src/stages/data_preprocessing.py
    deps:
      - src/stages/data_preprocessing.py
      - data/raw/student_scores.csv
    outs:
      - data/processed/processed.csv

  train:
    cmd: python src/stages/train.py
    deps:
      - src/stages/train.py
      - data/processed/processed.csv
    outs:
      - models/model.pkl

  evaluate:
    cmd: python src/stages/evaluate.py
    deps:
      - src/stages/evaluate.py
      - models/model.pkl
